apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcat
  namespace: webcat
  labels:
    app: webcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcat
  template:
    metadata:
      labels:
        app: webcat
    spec:
      containers:
        - name: webcat  
          image: cr.yandex/crp9hl1drtajjgkmmbvc/webcat:0.0.3
          # image: nginx
          ports:
            - containerPort: 8080